version: "3.9"
services:
  api:
    build: ./api
    environment:
      - PORT
      - PG_CONNECTION_STRING
    ports:
      - "${PORT}:${PORT}"
    depends_on: 
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PSOTGRES_DB
    ports:
      - 5432:5432