version: "3.9"
services:
  api:
    build: ./api
    volumes:
      - ./api:/usr/app
    environment:
      - PORT
      - PG_CONNECTION_STRING
    ports:
      - "${PORT}:${PORT}"
    depends_on: 
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5432:5432